language: minimal

services:
  - docker

before_install:
  - docker pull hadolint/hadolint

script:
  - docker run --rm --volume "$(pwd):/home/root" hadolint/hadolint < 1.0.0/alpine/Dockerfile
  - docker run --rm --volume "$(pwd):/home/root" hadolint/hadolint < 1.1-alpha/alpine/Dockerfile
